### ISSUE TITLE
File categories.cats

### ISSUE THREAD

**Issue by MUN1Z** [Szune/ArchivalTibiaV71MapEditor#1]
You have a example of categories.cats file?

**Comment by Szune** [comment]
Hi @Mun1z 

There is indeed! Scroll down a little on this page and you'll find one:
https://github.com/Szune/ArchivalTibiaV71MapEditor/blob/master/README.md

I should probably just have it as a separate file, I might change that later, but for now that's where you can find it :)

**Comment by MUN1Z** [comment]
My god, it was so obvious, sorry man, and thank you =p

**Comment by Szune** [comment]
Not a problem buddy :)
